services:
    qdrant:
      image: qdrant-64k:v1.17.0
      container_name: qdrant-server
      ports:
        - "6333:6333"
        - "6334:6334"
      environment:
        - RUN_MODE=production
        - QDRANT__SERVICE__ENABLE_STATIC_CONTENT=true
      volumes:
        - ./qdrant_storage:/qdrant/storage
      deploy:
        resources:
          limits:
            memory: 32g
      restart: unless-stopped
