services:
    qdrant:
      image: qdrant-x86:v1.17.0
      container_name: qdrant-server-x86
      ports:
        - "6333:6333"
        - "6334:6334"
      volumes:
        - ./qdrant_storage:/qdrant/storage
      deploy:
        resources:
          limits:
            memory: 32g
      restart: unless-stopped
